filetype plugin indent on
set backspace=2      " Backspace deletes like most programs in insert mode
set showcmd          " display incomplete commands
set incsearch        " do incremental searching

" Softtabs, 2 spaces
set tabstop=4
set shiftwidth=4
set shiftround
set expandtab

" Display relative line numbers, with absolute line number for current line
set number
set numberwidth=5
set relativenumber

" vim:ft=vim
